# Generated by Django 3.1.6 on 2021-05-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ingresa tu nombre')),
                ('email', models.EmailField(max_length=50, verbose_name='ingresa tu email')),
                ('phone', models.CharField(max_length=200, verbose_name='ingresa tu numero de celular')),
                ('message', models.TextField(verbose_name='Cuentame un poco sobre tí y porque te gustaría adoptarme!')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
