# Generated by Django 3.1.6 on 2021-06-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Cuentanos un poco sobre la mascota que quieres dar en adopción'),
        ),
    ]
