# Generated by Django 3.1.6 on 2021-06-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0003_auto_20210622_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'contacto', 'verbose_name_plural': 'contactos'},
        ),
        migrations.AddField(
            model_name='contact',
            name='ciudad',
            field=models.CharField(choices=[('Barbosa', 'Barbosa'), ('Bello', 'Bello'), ('Caldas', 'Caldas'), ('Copacabana', 'Copacabana'), ('Envigado', 'Envigado'), ('Girardota', 'Girardota'), ('Itagui', 'Itagui'), ('La Estrella', 'La Estrella'), ('Medellín', 'Medellín'), ('Sabaneta', 'Sabaneta')], default='Medellín', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
