# Generated by Django 3.1.6 on 2021-06-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0004_auto_20210622_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ciudad',
            field=models.CharField(choices=[('Barbosa', 'Barbosa'), ('Bello', 'Bello'), ('Caldas', 'Caldas'), ('Copacabana', 'Copacabana'), ('Envigado', 'Envigado'), ('Girardota', 'Girardota'), ('Itagui', 'Itagui'), ('La Estrella', 'La Estrella'), ('Medellín', 'Medellín'), ('Sabaneta', 'Sabaneta'), ('otra', 'otra')], max_length=30),
        ),
    ]
