# Generated by Django 3.1.6 on 2021-06-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0005_auto_20210622_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ciudad',
            field=models.CharField(max_length=30),
        ),
    ]
