# Generated by Django 3.1.6 on 2021-06-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0006_auto_20210622_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='mensaje',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='telefono',
        ),
    ]
