# Generated by Django 3.1.6 on 2021-06-16 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HogarPaso',
            fields=[
                ('idHogarPaso', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreRazon', models.CharField(max_length=50, verbose_name='Nombre/Razon Social')),
                ('tipoidentifica', models.CharField(choices=[('Cédula de ciudadanía', 'Cédula de ciudadanía'), ('NIT', 'NIT'), ('Pasaporte', 'Pasaporte'), ('Cédula de extranjería', 'Cédula de extranjería')], max_length=50, verbose_name='Tipo de indentificación')),
                ('numeroidentifica', models.CharField(max_length=50, verbose_name='Numero de identificación')),
                ('celular', models.CharField(max_length=30, verbose_name='Celular')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('ciudad', models.CharField(choices=[('Barbosa', 'Barbosa'), ('Bello', 'Bello'), ('Caldas', 'Caldas'), ('Copacabana', 'Copacabana'), ('Envigado', 'Envigado'), ('Girardota', 'Girardota'), ('Itagui', 'Itagui'), ('La Estrella', 'La Estrella'), ('Medellín', 'Medellín'), ('Sabaneta', 'Sabaneta')], max_length=30, verbose_name='Ciudad')),
                ('correoE', models.CharField(max_length=50, verbose_name='Correo electrónico')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idMascota', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreMascota', models.CharField(max_length=30, verbose_name='Nombre mascota')),
                ('especieMascota', models.CharField(choices=[('Canino', 'Canino'), ('Felino', 'Felino')], max_length=515, verbose_name='Tipo de Mascota')),
                ('edad', models.CharField(max_length=9, verbose_name='Edad,')),
                ('raza', models.CharField(max_length=30, verbose_name='Raza')),
                ('tamanoMascota', models.CharField(choices=[('Grande', 'Grande'), ('Mediano', 'Mediano'), ('Pequeño', 'Pequeño')], max_length=15, verbose_name='Tamaño')),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=15, verbose_name='Sexo')),
                ('vacunacion', models.CharField(choices=[('Vacunado', 'Vacunado'), ('No vacunado', 'No vacunado')], max_length=15, verbose_name='Estado de Vacunación')),
                ('esterilizacion', models.CharField(choices=[('Esterilizado', 'Esterilizado'), ('No esterilizado', 'No esterilizado')], max_length=30, verbose_name='Estado de Esterilización')),
                ('imagen', models.ImageField(upload_to='Mascotas')),
                ('HogarPaso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscador.hogarpaso')),
            ],
        ),
    ]
