# Generated by Django 3.1.6 on 2021-06-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hogarpaso',
            name='ciudad',
            field=models.CharField(choices=[('Barbosa', 'Barbosa'), ('Bello', 'Bello'), ('Caldas', 'Caldas'), ('Copacabana', 'Copacabana'), ('Envigado', 'Envigado'), ('Girardota', 'Girardota'), ('Itagui', 'Itagui'), ('La Estrella', 'La Estrella'), ('Medellín', 'Medellín'), ('Sabaneta', 'Sabaneta')], max_length=30, verbose_name='Ubicación'),
        ),
    ]
