# Generated by Django 3.1.6 on 2021-06-19 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0003_auto_20210616_0140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hogarpaso',
            options={'verbose_name': 'Hogar de paso', 'verbose_name_plural': 'Hogares de Paso'},
        ),
    ]
