# Generated by Django 3.1.6 on 2021-06-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mascota_raza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='especieMascota',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=515, verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='genero',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=15, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tamanoMascota',
            field=models.CharField(choices=[('Grande', 'Grande'), ('Mediano', 'Mediano'), ('Pequeño', 'Pequeño')], max_length=15, verbose_name='Tamaño'),
        ),
    ]
