# Generated by Django 3.1.6 on 2021-06-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210615_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='especieMascota',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=515, verbose_name='Tipo de Mascota'),
        ),
    ]
