# Generated by Django 3.1.6 on 2021-06-19 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0004_auto_20210618_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mascota',
            options={'verbose_name': 'Mascota', 'verbose_name_plural': 'Mascotas'},
        ),
    ]
